title:              SOCAR Tech Blog
email:              recruit@socar.kr
description:        쏘카 기술 블로그
author:             SOCAR
baseurl:            ""
url:                "https://tech.socarcorp.kr"
exposeEmail:        false

# Social Profiles
twitter_username:   
github_username:    # socar-inc
facebook_username:  socarsharing
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   "UA-30551922-27"

# Build settings
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# 기타_불필요_폴더_또는_파일 제거
exclude:
  - node_modules
  - .git
  - .github
  - .DS_Store
  - vendor
  - tmp
  - .cache
  - "*.log"
  - README.md
  - CODEOWNERS